Changes To Outpost for VOE
AndroidQuazar/VanillaExpandedFramework pull request #52
Opened 2022-07-22 17:26 UTC by ANRimworld

Changes:
https://docs.google.com/document/d/1GqTIbLsPy0gdcAqceleyB4_3fZsEyCxAl_EDi4c6pBg/edit?usp=sharing

2022-07-22 17:45 UTC, legodude17 requested changes
Really good, thank you so much for doing this. A few small changes I'd like, but other than that this is a really good PR.

2022-07-22 17:45 UTC, legodude17 commented on Source/Outposts/Outpost/Outpost.cs
> +                        foreach (var map in Find.Maps.Where(m => m.IsPlayerHome).OrderByDescending(m => Find.WorldGrid.ApproxDistanceInTiles(m.Parent.Tile, Tile)))
```suggestion
                        foreach (var map in Find.Maps.Where(m => m.IsPlayerHome).OrderBy(m => Find.WorldGrid.ApproxDistanceInTiles(m.Parent.Tile, Tile)))
```
Same as above. Doesn't matter as much here, but consistency is nice.

2022-07-22 17:45 UTC, legodude17 commented on Source/Outposts/Outpost/Outpost.cs
> +                deliveryMap = Find.Maps.Where(m => m.IsPlayerHome).OrderByDescending(m => Find.WorldGrid.ApproxDistanceInTiles(m.Parent.Tile, Tile)).FirstOrDefault();
```suggestion
                deliveryMap = Find.Maps.Where(m => m.IsPlayerHome).OrderBy(m => Find.WorldGrid.ApproxDistanceInTiles(m.Parent.Tile, Tile)).FirstOrDefault();
```
Since we're getting the first and we want the smallest, this will put the smallest first.

2022-07-22 17:45 UTC, legodude17 commented on Source/Outposts/Outpost/Outpost_Deliveries.cs
> +            var map = deliveryMap != null ? deliveryMap :Find.Maps.Where(m => m.IsPlayerHome).OrderByDescending(m => Find.WorldGrid.ApproxDistanceInTiles(m.Parent.Tile, Tile)).FirstOrDefault();
Is this necessary with the `SpawnSetup` one? I think one or the other would suffice. I vote this one.
```suggestion
            var map = deliveryMap != null ? deliveryMap : Find.Maps.Where(m => m.IsPlayerHome).OrderBy(m => Find.WorldGrid.ApproxDistanceInTiles(m.Parent.Tile, Tile)).FirstOrDefault();
```

2022-07-22 17:45 UTC, legodude17 commented on Source/Outposts/Outpost/Outpost_Deliveries.cs
> +            if (!map?.Parent?.HasMap ?? true) //chance of this is super low, but it's possible for those dumb enough to play nomads
Ah good idea.

2022-07-22 17:45 UTC, legodude17 commented on Source/Outposts/Outpost/Outpost_Needs.cs
> +            if(pawn.health?.hediffSet == null || pawn.Dead) { return; } //Just in case the birthday killed them XD
Hmm if this is a possibility we may want to add handling to move the corpse to the outpost items storage when they die.

2022-07-22 17:45 UTC, legodude17 commented on Source/Outposts/Outpost/Outpost_Utilities.cs
> +        //Theres a few things that seem to leave 0 or destroyed things in contained. I fixed tend, I think the other ones is stuff decaying maybe? Not sure typically its food stuff doing it
Decaying would be weird since it shouldn't be ticking.

2022-07-22 17:45 UTC, legodude17 commented on Source/Outposts/Outposts.csproj
> +    <None Include="packages.config" />
Can you use `<PackageReference>` instead of `packages.config`?

2022-07-22 18:37 UTC, ANRimworld commented on Source/Outposts/Outpost/Outpost_Utilities.cs
> +        //Theres a few things that seem to leave 0 or destroyed things in contained. I fixed tend, I think the other ones is stuff decaying maybe? Not sure typically its food stuff doing it
Yeah, tbh I have no clue how the 0 stack ones got there. The destroyed ones I traced back to the expose data/add pawn thing. Might be the same thing for 0 stack. Better to be safe, and definitely existing saves have them in there that will cause complaints when you try to take them out so good to get them cleaned up.

2022-07-22 18:45 UTC, ANRimworld commented on Source/Outposts/Outpost/Outpost_Needs.cs
> +            if(pawn.health?.hediffSet == null || pawn.Dead) { return; } //Just in case the birthday killed them XD
Good call, health tick could kill as well. Added that.

2022-07-23 04:04 UTC, legodude17 approved these changes
Looks good!

2022-07-23 04:04 UTC, legodude17 commented on Source/Outposts/Outpost/Outpost_Needs.cs
> +                containedItems.Add(pawn.Corpse);
May not work correctly due to how corpse spawning works.

2022-07-23 04:04 UTC, legodude17 commented on Source/Outposts/Outposts.csproj
> +    </PackageReference>
```suggestion
    <PackageReference Include="Lib.Harmony">
      <Version>2.2.2</Version>
      <ExcludeAssets>runtime;</ExcludeAssets>
    </PackageReference>
```
This just ensures the `0Harmony` dll doesn't end up in the mod by accident.

2022-07-23 04:07 UTC, merged